### PR TITLE
feat: added showLabels setting

### LINKED ISSUE #14: Labeling arcs
I'm building [ActivityWatch](https://github.com/ActivityWatch/activitywatch) and we're using this lib for our sunburst visualization of time spent per category. ([again](https://github.com/David-Desmaisons/Vue.D3.sunburst/issues/11#issue-509316033), thanks!)

We've implemented the hover feature to show information about the represented data, but it's hard to get an overview at a glance, which makes me want to implement labeling of the arcs similar to what I've had in some of my Python visualizations:

image

I'm not super skilled at D3, but I'm just posting it here in case it piques someone's attention/interest, and to keep myself accountable in case I drop the ball.

Something akin to this: http://bl.ocks.org/metmajer/5480307

I found this for creating rounded text (might not be the best way to go, but still): https://www.visualcinnamon.com/2015/09/placing-text-on-arcs.html

### PR DESCRIPTION
**Pull request by ErikBjare**
Fixes #14 

Looked at how it was done in http://bl.ocks.org/metmajer/5480307 for inspiration.

Issues:

 - [x] The showLabels setting doesn't apply when toggled
 - [x] mouseover/click handlers are set on the path, should be set on the group
 - [x] getPathes should probably `selectAll('g')`
 - [x] When showLabels is toggled off there are text elements remaining (I'm not good enough at D3 to understand why)
 - [x] Labels don't disappear/update on click/zoom (might be related to the previous issue)
 - [x] Labels for the left half become upside down
 - [x] Long labels are overflowing (not sure if there's a good way to fix this, fixing it is not a priority for me)

### CODE REVIEW

**Comment by ErikBjare** [comment]
@David-Desmaisons Would love a review and help with the remaining issues, if you can spare the time. :slightly_smiling_face:

**Comment by David-Desmaisons** [comment]
Thanks @ErikBjare I will review it this week-end

**Comment by David-Desmaisons** [comment]
@ErikBjare took a brief look at the PR and made some merge/clean-up.

It seems that there is something wrong somewhere in the logic of selecting g or path element: try chaning the color scale with labels: this will be broken.

Please feel free to go ahead and try to fix it.

**Comment by ErikBjare** [comment]
@David-Desmaisons I rebased and fixed the issue. Should be ready for review now.

**Comment by ErikBjare** [comment]
@David-Desmaisons Don't mean to nag, but I just wanted to remind you that I'm waiting for your review. :slightly_smiling_face:

**Comment by David-Desmaisons** [comment]
@ErikBjare I didn't see your last answer...I will take a look soon.

**Pull request merged**
