### PR TITLE
add scale parameter and linting

### PR DESCRIPTION
**Pull request by matthieucov**
This PR allows users to pass their own colorScale.
In the example, I am using the same `scaleOrdinal` that you are using but we could use something else.

Let me know what you think

### CODE REVIEW

**Comment by David-Desmaisons** [comment]
Thanks for this one.
Could you update the README with the desciption of the new props?

**Comment by matthieucov** [comment]
@David-Desmaisons Updated the readme. Are you planning on doing a release soon ?

**Comment by David-Desmaisons** [comment]
I will need sometime to test the chnage. Hopefully if everything goes OK, I can make a new release by the end of this week.

**Comment by matthieucov** [comment]
@David-Desmaisons bumping the PR

**Comment by David-Desmaisons** [comment]
@matthieucov I will check with week.

**Comment by matthieucov** [comment]
@David-Desmaisons Sorry for bumping this again, do you think you will be able to do it by the end of the week?

**Comment by David-Desmaisons** [comment]
In your branch, when using the live example only the override of the color scale is used indenpently if you change the scale value using the droplist.
Could you add a checkbox to activate the color scheme override, so that we can test both override and standard color scale?

**Pull request merged**
